from pathlib import Path


output = Path("review-context/semanticdb.md")

files = sorted(
    Path("semanticdb").rglob("*.semanticdb")
)

with output.open(
    "w",
    encoding="utf-8",
) as out:

    out.write(
        "# SCALA SEMANTICDB\n\n"
    )


    # out.write(
    #     f"SemanticDB files: {len(files)}\n\n"
    # )
    #
    # for file in files:
    #
    #     out.write(
    #         f"## {file}\n\n"
    #     )
    #
    #     out.write(
    #         "A SemanticDB artifact exists for "
    #         "this source area.\n\n"
    #     )
    #
    #     out.write(
    #         "The artifact was generated by the "
    #         "Scala CI compilation.\n\n"
    #     )


#print(
#    output.read_text(
#        encoding="utf-8"
#    )
